### ISSUE TITLE
G1 point exceeding modulus

### ISSUE THREAD

**Issue by holiman** [ConsenSys/gnark-crypto#103]
We are running gnark-crypto against other bls implementations on oss-fuzz, and have found a crash. Essentially, the code which crashes it this (printouts added by me) : 
```
	// sample a random scalar
	s, err := randomScalar(input, fp.Modulus())
	if err != nil {
		return nil, nil, err
	}
	fmt.Printf("Scalar: %x\n", s)
	// compute a random point
	cp := new(gnark.G1Affine)
	_, _, g1Gen, _ := gnark.Generators()
	cp.ScalarMultiplication(&g1Gen, s)
	cpBytes := cp.Marshal()
	fmt.Printf("Scalar mult, bytes: %x\n", cpBytes)

	// marshal gnark point -> geth point
	g1 := bls12381.NewG1()
	kp, err := g1.FromBytes(cpBytes)
```
And what happens is 
```
Scalar: 73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff0000000100000000000000
Scalar mult, bytes: 400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
panic: Could not marshal gnark.G1 -> geth.G1: must be less than modulus

goroutine 1 [running]:
github.com/ethereum/go-ethereum/tests/fuzzers/bls12381.getG1Points({0x709380, 0xc00002ecf0})
        /home/user/go/src/github.com/ethereum/go-ethereum/tests/fuzzers/bls12381/bls12381_fuzz.go:205 +0x64b
```
So we do a scalar mult, then marshal the result into `cpBytes`. Then we try to unmarshal those bytes into a `bls12381` . And then we find that the first field element is smaller than the modulus, which it apparently rejects. 

I'm not sufficiently knowledgeable here to know what is happening or why, so would appreciate some help assessing this. 
I did test this against the latest version of gnark-crypto also, but go the same result.

**Comment by ThomasPiellard** [comment]
Hi @holiman , thanks for raising the issue, our code didn't take into account the variable size of the scalar. Currently the size of the loop in the scalar multiplication is hardcoded to match the group size. We are fixing it now.

**Comment by ThomasPiellard** [comment]
Hi @holiman , so the scalar that you have is in fact a multiple of r, the group order of bls12-381. So the result of the scalar multiplication is the point at infinity, encoded as [0,0]. gnark-crypto and geth use a different encoding for the point at infinity in affine, for geth it's [0,0], for gnark-crypto it's 0x40 << 760, so it's indeed bigger than bls12-381's field of definition. The reason for our way of serializing is to match ZCash and IETF encoding.

**Comment by gbotrel** [comment]
To give more context on this one; 

1. We did investigate and found no bug on our side related to either the `ScalarMul` or the [de]serialization. 
2. As for the encoding differences, we follow the [latest IETF draft](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-pairing-friendly-curves-10#appendix-C), and Ethereum 2.0 (through the use of supranational/blst) [does too](https://github.com/ethereum/consensus-spec-tests/issues/24). In particular:

```
The most-significant three bits of a G1 or G2 encoding should be masked away before the coordinate(s) are interpreted. These bits are used to unambiguously represent the underlying element:

...
The second-most significant bit indicates that the point is at infinity. If this bit is set, the remaining bits of the group element's encoding should be set to zero.
```
