### ISSUE TITLE
Failing tests for dense modulus

### ISSUE THREAD

**Issue by kilic** [ConsenSys/gnark-crypto#104]
Some tests are failing for generated secp256k1 fields which has 256 bit dense modulus value. To regenerate in a clean directory:

```
goff -m 115792089237316195423570985008687907853269984665640564039457584007908834671663 -o . -p secp256k1_fp -e Element
go mod init tmp && go mod tidy
go test
```

**Comment by gbotrel** [comment]
@kilic thanks for raising this issue :) 

The field arithmetic code generation for multiplication [saturated moduli only] was missing a carry propagation. Fixed, and `goff` is updated to latest `gnark-crypto` .

**Comment by gbotrel** [comment]
On a side note, we are also looking at `secp256k1` fields  (not the curve operations), and might end up re-working these type of moduli in the future, perf-wise.
