### ISSUE TITLE
Faster subgroup checks on G2 on most curves

### ISSUE THREAD

**Issue by mratsim** [ConsenSys/gnark-crypto#122]
I've had a look in the library and it seems like Scott optimization in was implemented only for BLS12-381
(paper: https://eprint.iacr.org/2021/1130.pdf)

It is however applicable for all curves where gcd(h₁, h₂) == 1 with h₁ and h₂ the cofactors on G₁ and G₂.
In that case it is enough to check that `ψ(P) = [t-1]P` with t the trace.

As h₁ = 1 for BN curves and t-1 = 6u², it is applicable to BN254.
It is noted in the discussion that it also works for BLS24 curves.

**Comment by yelhousni** [comment]
Hi @mratsim, I think that the G2 trick is implemented for [BLS12-381](https://github.com/ConsenSys/gnark-crypto/blob/d3277c3191f374355a2e3e3edd314552c4fd4ce3/ecc/bls12-381/g2.go#L376), [BLS12-377](https://github.com/ConsenSys/gnark-crypto/blob/d3277c3191f374355a2e3e3edd314552c4fd4ce3/ecc/bls12-377/g2.go#L376) and [BN254](https://github.com/ConsenSys/gnark-crypto/blob/d3277c3191f374355a2e3e3edd314552c4fd4ce3/ecc/bn254/g2.go#L376) (but not BLS24-315 indeed).

**Comment by mratsim** [comment]
Oh indeed, I have a clone older than https://github.com/ConsenSys/gnark-crypto/pull/95/files

**Comment by yelhousni** [comment]
So there was an error in Scott preprint for G2 membership test proof. However, the result is still correct (more on that here: https://eprint.iacr.org/2022/352.pdf).
