### ISSUE TITLE
FFT: modify the cosets

### ISSUE THREAD

**Issue by ThomasPiellard** [ConsenSys/gnark-crypto#141]
In the FFT, we do not need to handle cosets in a bigger 2^n cyclic group, a coset inside Fr is enough, and would mitigate the limitation of number of constraints of Groth16 (we could use the full 2 adicity offered by Fr). Also it would simplify the FFT api.

**Comment by gbotrel** [comment]
@ThomasPiellard this is done right?

**Comment by ThomasPiellard** [comment]
Yes I forgot to close the issue
