### ISSUE TITLE
`SqrtRatio` bug

### ISSUE THREAD

**Issue by yelhousni** [ConsenSys/gnark-crypto#158]
It seems there is a bug in `SqrtRatio` in `Fp2` for BLS12-377. This corresponds to the "any field" case in the template. The same case-template was used for BLS12-381's `Fp2` and works fine. The only difference is constants or we should look for the bug somewhere else.

**Comment by yelhousni** [comment]
There was no bug in `SqrtRatio` implementation. However, it seems that when `CoordExtRoot` is not specified in the config file of the curve, the code takes the quadratic non-residue to be 0 as it is an unassigned `int64` in the `Point` struct. Hence the SSWU parameters become incorrect. So either we keep it this way and it's up to the implementer to provide a correct `CoordExtRoot` or we raise an error when `CoordExtRoot` is unassigned or we even check that it is a proper quadratic non-residue. 

Closing this issue.

**Comment by Tabaie** [comment]
I'm not completely happy with the name `CoordExtRoot`, suggestions? Also generally the EC configurations seem a bit awkward to me. There is some redundancy in it I think. Should we think about simplifying it?
