### ISSUE TITLE
Buffer in mimc should reason on p-digits, not block size

### ISSUE THREAD

**Issue by ThomasPiellard** [ConsenSys/gnark-crypto#190]
In the mimc implementations, this for loop
```
for i := 0; i < nbChunks; i++ {
		copy(buffer[:], d.data[i*BlockSize:(i+1)*BlockSize])
		x.SetBytes(buffer[:])
		r := d.encrypt(x)
		d.h.Add(&r, &d.h).Add(&d.h, &x)
	}
```
might create collision, as the modulus is not BlockSize long but usually shorter.

What should be done is to take the value in the buffer, decompose it base `p` where `p` is the size of the snark field, and encrypt each digit one after the other, using the previous hash as initial state.

**Comment by realuncle** [comment]
@ThomasPiellard  Any update regarding this issue?

**Comment by ThomasPiellard** [comment]
Hi @realuncle no currently the issue hasn't been fixed. I wonder if it's not better to directly enforce the Write() function in the mimc implementation to not accept anything which overflows r, the snark modulus. Otherwise if we pass a gigantic slice of []byte for instance it would force us to do the r-basis decomposition, which would be quite inefficient.
