### ISSUE TITLE
Implement SSWU HashToCurve

### ISSUE THREAD

**Issue by eabz** [ConsenSys/gnark-crypto#24]
Hello. 
As I already requested over the Discord, it will be awesome if you can add the SSWU HashToCurve functions for `bls381`

I have been using the https://github.com/kilic/bls12-381 library for our blockchain (https://github.com/olympus-protocol/ogen) since it is the only pure go BLS library which follows the latest drafts.

Recently I have discovered that kilic library is not very fast (compared with herumi mcl or blst) and that's where I found gurvy. 

I really hope you can add it since there is no efficient BLS pure go implementation right now.

**Comment by gbotrel** [comment]
Hi, this is definitely on the backlog, but not high priority at the moment. 
Will keep this open and update when we start working on that.

**Comment by xenowits** [comment]
Hi @gbotrel . You can assign this task to me. I'll take this up!
