### ISSUE TITLE
Q: Can a custom curve be implemented using `gnark-crypto` generators?

### ISSUE THREAD

**Issue by omerfirmak** [ConsenSys/gnark-crypto#273]
We are looking to implement [Stark Curve](https://docs.starknet.io/documentation/architecture_and_concepts/Hashing/hash-functions/#stark_curve) in Go

**Comment by gbotrel** [comment]
Yes it can, maybe @yelhousni can give couple of indications on what would be generated and what needs to be "hand-written" for that specific curve

**Comment by omerfirmak** [comment]
Hey @yelhousni , thanks for the info. We are a team at Nethermind, implementing a StarkNet full node in Golang. I have created an [issue](https://github.com/NethermindEth/juno/issues/466) to track this effort on our side as well. 

Our current solution is wrapping a CPP library that Starkware wrote, but I am sure we can get much better performance by building on top of all the work you have done here.

**Comment by omerfirmak** [comment]
> as a starter, we only need scalar multiplication and addition on the curve

From the config files @yelhousni, which parts would be the bare minimum to get these working? 

StarkWare can define a curve in Python with these fields only.
[
curve = Curve("Curve0", FIELD_PRIME, ALPHA, BETA, EC_ORDER, *SHIFT_POINT)](https://github.com/starkware-libs/cairo-lang/blob/de741b92657f245a50caab99cfaef093152fd8be/src/starkware/crypto/signature/fast_pedersen_hash.py#L15)

and those values are defined in;

https://github.com/starkware-libs/cairo-lang/blob/de741b92657f245a50caab99cfaef093152fd8be/src/starkware/crypto/signature/pedersen_params.json#L20-L24

**Comment by yelhousni** [comment]
@omerfirmak I drafted a minimal implementation of the stark curve in this branch [feat/stark-curve](https://github.com/ConsenSys/gnark-crypto/tree/feat/stark-curve). Everything seems to be working except the Svdw hash-to-curve. I will look at his later.

**Comment by gbotrel** [comment]
quick (perf) note; the field arithmetic generated for this modulus, given its form, can be optimized quite a lot (and consequently the curve ops).

**Comment by yelhousni** [comment]
> @omerfirmak Everything seems to be working except the Svdw hash-to-curve. I will look at his later.


Ok everything works fine including svdw hash-to-curve (`A != 0`). You can use this branch now and in the meantime I will work on the code generation and some optimizations to merge it to gnark-crypto master branch.

**Comment by joshklop** [comment]
Hi @yelhousni. (I work with @omerfirmak) This is awesome, thanks so much for your work on this! We'll try it out ASAP.

**Comment by omerfirmak** [comment]
> > @omerfirmak Everything seems to be working except the Svdw hash-to-curve. I will look at his later.
> 
> Ok everything works fine including svdw hash-to-curve (`A != 0`). You can use this branch now and in the meantime I will work on the code generation and some optimizations to merge it to gnark-crypto master branch.

Hey @yelhousni thank you for this, is works great for us! When can we expect this to land to `master`?

https://github.com/NethermindEth/juno/pull/476 gives us almost 3x improvement over our existing solution.

**Comment by yelhousni** [comment]
@omerfirmak Also if you have any contributions you would like to upstream to gnark-crypto (e.g. Pedersen hash), feel free to do so!

**Comment by omerfirmak** [comment]
> @omerfirmak Also if you have any contributions you would like to upstream to gnark-crypto (e.g. Pedersen hash), feel free to do so!

Yeah, will most definitely do once the PR is merged!

**Comment by yelhousni** [comment]
#299

**Comment by anshulforyou** [comment]
> @omerfirmak Also if you have any contributions you would like to upstream to gnark-crypto (e.g. Pedersen hash), feel free to do so!

Hey @yelhousni, I work with @omerfirmak. We were trying to add our [pedersen-hash](https://github.com/NethermindEth/juno/blob/develop/core/crypto/pedersen_hash.go#L68) implementation to stark-curve of gnark-crypto's but we are facing some difficulty understanding where exactly we should place it. Can u please help us out in it?

**Comment by yelhousni** [comment]
Hey @anshulforyou, sure we can have a sync up call if you want. Drop me a message on youssef.elhousni@consensys.net.
