### ISSUE TITLE
Consider adding a method to check that a serialised field element is canonical

### ISSUE THREAD

**Issue by kevaundray** [ConsenSys/gnark-crypto#274]
**Problem**

Sometimes when one receives a serialised field element, we want to ensure that this is a canonical representation of the field element. In most cases, canonical means checking that the integer represented by the field element F_p is in the range [0,p) .

**Solution** 

One possible solution for this is to introduce a `SetBytesCanonical` or `SetBytesReduced` or SetBytes(bytes []byte) -> (isReduced bool, elem *Element)` method for example in the public API

**Comment by gbotrel** [comment]
So essentially, `SetBytesCanonical` should fail if the input is not in [0, p), correct?

**Comment by gbotrel** [comment]
That being said, having `SetBytes`, `SetBytesLE` and `SetBytesCanonical` might be a bit too much. Considering exposing them as package level method in something similar to go std encoding/binary: https://pkg.go.dev/encoding/binary#ByteOrder .

**Comment by kevaundray** [comment]
> So essentially, `SetBytesCanonical` should fail if the input is not in [0, p), correct?

Yep this is correct!
