### ISSUE TITLE
What are the usecases for ToBigInt method?

### ISSUE THREAD

**Issue by kevaundray** [ConsenSys/gnark-crypto#276]
**Motivation**

When I think about the public methods on a field struct, I usually assume that they do not leak any internal implementation detail. In this case, the fact that Montgomery multiplication/representation is being used instead of Barret Multiplication for example, seems to be being leaked by ToBigInt which returns the element in montgomery form as a golang big integer.

**Discussion**

It then prompted me to ask, if there are any usecases for having this exposed that I'm not aware of?

The main downside I can see is that, as an external user, if you do not know what montgomery form is and or you are not reading the documentation, you may call `ToBigInt` thinking that it's behaviour is akin to `ToBigIntRegular`.

**Limitations Imposed**

If the fact that montgomery is being used is not exposed through the public API, then this means that the following invariants will hold:

- All big integers created from a field element, will be in "regular" form
- Creating a field element can only be done via either copying another field element or inputting a byte array/integer which is in "regular" form.

- `ToBigInt` would then be `toBigInt`
- `FromMont` which converts a field element from montgomery form to regular form, would most likely be removed. (Meaning there would be no public methods which violate the rule that all field elements are internally in montgomery form)

**Main arguments against**

The whole post assumes that the user is not experienced and likely to shoot themselves in the foot, this may not be the intended target audience and the API may be good just the way it is :)

**Comment by kevaundray** [comment]
I think this line of reasoning would also apply to `FromMont` being in the public API. 

It's also likely that this is the only interface that works due to language constraints :)

**Comment by gbotrel** [comment]
At first sight, I think yes, deprecating `ToBigInt` (to avoid behavior change with lib update) may make sense. Probably here for historical reasons.

`FromMont` on the elements however is needed; we may work at the bit level with field elements in various places, and need the element to be represented in canonical form to do so.

**Comment by kevaundray** [comment]
> 

I would naively suggest a `toBytes` or `toBits` method here, but I guess you are also worried about perf?

**Comment by gbotrel** [comment]
We might work around it -- though indeed, doing it in place helps with perf. 
I suspect going the `ToBits()` will add more code than it will remove accros the code base.

**Comment by kevaundray** [comment]
> We might work around it -- though indeed, doing it in place helps with perf.
> I suspect going the `ToBits()` will add more code than it will remove accros the code base.

Makes sense, I will lean on your knowledge of the codebase here :)

**Comment by gbotrel** [comment]
after a second read on this, I'm more convinced that this is something we should do :) 
In particular because of this: 
> (Meaning there would be no public methods which violate the rule that all field elements are internally in montgomery form)

@Tabaie / @ThomasPiellard any strong opinion against this? I think the only noticeable (?) perf impact would be in groth16 prover; we would need to do an extra `~2n` calls to `ToBits` in the msm (n being length of solution vector; ToBits --> would cost less than a `Mul`).

**Comment by Tabaie** [comment]
I've definitely lost a few days of my life to confusion between `.ToBigInt` and `ToBigIntRegular`. Wouldn't at all be sad to see the former go. The arguments around the "invariant" and hiding implementation details make sense.

Just to make sure I understand correctly, would we have to give up the option for doing MSM with non-Mont elements, in order to respect the invariant?

**Comment by kevaundray** [comment]
> I've definitely lost a few days of my life to confusion between `.ToBigInt` and `ToBigIntRegular`. Wouldn't at all be sad to see the former go. The arguments around the "invariant" and hiding implementation details make sense.
> 
> Just to make sure I understand correctly, would we have to give up the option for doing MSM with non-Mont elements, in order to respect the invariant?

This sounds correct to me, so [this if statement ](https://github.com/ConsenSys/gnark-crypto/blob/1572c4e3cda6663b8d00ae05291e4b1d4f585cd8/ecc/bls12-381/multiexp.go#L95) would be removed I think and we convert the scalars out of montgomery form unconditionally.
