### ISSUE TITLE
Consider adding SetBytesLE and BytesLE

### ISSUE THREAD

**Issue by kevaundray** [ConsenSys/gnark-crypto#279]
**Motivation**

Not every protocol will use big endian when serialising field elements. This means that when using gnark-crypto, one must reverse the bytes before and after de/serialisation.

**Suggestion** 

Adding a SetBytesLE and BytesLE wrapper method which reverses the bytes would be useful. If breaking changes are allowed, then change SetBytes/Bytes to SetBytesBE/BytesBE method might make for a better/more explicit API

**Observation**

It seems that Big endian was possibly used as a default due to the usage of big.Int internally in the field element code

**Comment by gbotrel** [comment]
Yep, seems reasonable. We had to do that couple of times on forks / branches for compatibility purposes. 
Lots of Golang based code indeed use Big endian 👍 .
