### ISSUE TITLE
field arithmetic: add package level methods to perform some operations without reduction?

### ISSUE THREAD

**Issue by gbotrel** [Consensys/gnark-crypto#280]
So far, we only represent elements in Montgomery form / reduced. This allow for a simple API and a single type of underlying `Element` representation.

Some algorithms / users expressed the needs to perform:

1. `Multiplication` without reduction --> produce a `WideElement`
2. `Reduction` of a `WideElement`
3. `Multiplication` by a word (uint64) or even smaller (uint16?).

One thing to be careful about is our `Mul` doesn't accept input in [0, 2q) but in [0, q). 

@yelhousni & @AlexandreBelling can you comment / complete the wish list?

**Comment by yelhousni** [comment]
This should speed up some computations in pairings: lazy reduction, mul by small constants (coeff b of the twist).. This would also allow us to try [Longa22](https://eprint.iacr.org/2022/367.pdf)'s interleaved mul. We might also save a reduction in the batch affine add.

**Comment by AlexandreBelling** [comment]
I assume, it allows saving a lot of time for long addition as well. Lazy reduction can also help for FFT.

**Comment by gbotrel** [comment]
I think this is probably low priority until we identify clear perf bottlenecks.
