### ISSUE TITLE
Building c-shared libraries

### ISSUE THREAD

**Issue by PatStiles** [ConsenSys/gnark-crypto#283]
Hello I'm currently attempting to build gnark-crypto to c-shared libraries to use in ffi or rust. Cloned the repo and tried to build using `go build -o gnark-crypto.so -buildmode c-shared internal/generator/main.go` . Which results in the following, but does not generate a .so file. 
![image](https://user-images.githubusercontent.com/33334338/207670584-183e8bad-69ef-408a-be64-446ee1b9e1ae.png)

**Comment by gbotrel** [comment]
just tried on my local macbook pro, can't reproduce the issue (command generates the .so), might be a go env / linker issue?

**Comment by PatStiles** [comment]
Was able to resolve, was due to a conflict with an older go version. As a follow up, is would main.go be the correct root to compile to libraries from for ffi use? Specifically intrested in using this for pairings. Happy to take this discussion elsewhere as well.

**Comment by gbotrel** [comment]
No this is the entry point to do code generation (internal).
Best compile the package you're directly interested in.
