### ISSUE TITLE
Custom unmarshal for field elements

### ISSUE THREAD

**Issue by joshklop** [ConsenSys/gnark-crypto#289]
Right now, it appears gnark-crypto unmarshals field elements from json by using the [`vv.SetString(s, 0)`](https://github.com/ConsenSys/gnark-crypto/blob/7fcb6a36443a7c998756e3910d0d99aeb37d0213/internal/field/internal/templates/element/conv.go#L265) big.Int method. This requires the string to include a prefix `0x`, `0b`, etc. 

For our use case, we need to unmarshal JSON with hex strings that may or may not include the prefixes. Is it possible to replace the call to `SetString` in `UnmarshalJSON` with a callback that users can override? The default could be something like:

```go
var CustomUnmarshalJSON := func(s string, x *big.Int) error {
        if _, ok := x.SetString(s, 0); !ok {
                return errors.New("can't parse into a big.Int: " + s)
        }
        return nil
}
``` 

I would be happy to contribute a PR if you think this is an acceptable solution.

**Comment by gbotrel** [comment]
mmhh not a big fan of this approach; why not have your own `UnmarshalJSON` in the parent struct?

**Comment by gbotrel** [comment]
(note that as you probably saw on the big.Int doc, no prefix on the string defaults to base10, which seems a reasonable behavior)

**Comment by joshklop** [comment]
Thanks for the quick response.

> why not have your own `UnmarshalJSON` in the parent struct?

I feel I am missing something here. `SetString` does not accept a hex string without a prefix because it assumes base10. We could have an intermediate struct that treats field elements as `string`s instead of `fp.Element`s. Then we manually convert that intermediate struct to our desired struct.

I could be missing a simpler alternative.

**Comment by gbotrel** [comment]
Oh what I meant is if you have a parent struct like so;
```go
type Parent struct {
A Element
}
```
You can write the `UnmarshalJSON` directly for the parent struct, and bypass the `Element` `UnmarshalJSON`.

**Comment by joshklop** [comment]
Thanks for the clarification. I ended up writing a (quite hacky) [implementation](https://github.com/NethermindEth/juno/blob/e4e3ad85a16ad9536318f43073f1bc1979d9cde1/clients/gateway.go#L298-L405) of a custom unmarshaller for an arbitrary struct.

In case it helps anyone else, it can be found here.
