### ISSUE TITLE
Clarification about benchmarks

### ISSUE THREAD

**Issue by jon-chuang** [ConsenSys/gnark-crypto#30]
https://hackmd.io/@zkteam/eccbench

I would like to clarify the benchmarks above, since when I benchmarked it locally, some discrepancies appeared.

In particular, I noticed the `BenchmarkG1AffineDouble-16` bench was much slower, relative to other timings, than in the above listed benchmarks. Hence, my questions is whether any of the benches listed were based on the extended rather than jacobian representation.

I notice the consistency of this discrepancy. mcl is faster for mixed add but gurvy supposedly faster for double. But when I bench on my machine, double is very slow, and only the extended double has the claimed speed. Hence, my suggestion is to redo the data collection since now I think there is reason to doubt it.

Another question I have is with regards to the odd naming convention. In particular, why one lists `BenchmarkG1AffineDouble-16` instead of `BenchmarkG1JacDouble-16`, since one is not using affine coordinates...

**Comment by yelhousni** [comment]
Hi @jon-chuang, I indeed got confused with the naming convention. `BenchmarkG1AffineDouble` is indeed in Jacobian coordinates and the reported timings for gurvy `double` are in extended Jacobian. I will update the corresponding data. 

To be fair to all libs, I am updating the post as follows:
- [x] correct `arkworks-rs` timings following a assembly bug (https://github.com/arkworks-rs/algebra/pull/192#)
- [ ] add `relic` assembly preset (`x64-pbc-bls12-381`)
- [ ] update `kilic/bls12-381` after recent imporovements 
- [ ] update `constantine` after recent imporovements
- [ ] add `iden3/ffiasm` to the benchmark

Thank you for opening the issue! Let me know if you notice anything else.

**Comment by jon-chuang** [comment]
Hi @yelhousni thanks! 

I'm not too familiar with the extended jacobian coordinates, do you know how they are used in gurvy specifically? Meaning, are they used in scalar mul or msm for instance? Just curious as they seem to provide some nice speed results, I was wondering if it's been tested to work well as part of bigger routines.

Currently we are making some simple changes to improve performance across the board arkworks-rs/algebra/#205 prompted by these benchmarks, it would be nice to include these improvements, alongside measuring the asm for arkworks.🙏

**Comment by yelhousni** [comment]
Extended Jacobian coordinates are indeed used in gurvy for MSM. Let me know when you finish improving `arkworks-rs`
