### ISSUE TITLE
Optimise field arithmetic for the STARK curve modulus

### ISSUE THREAD

**Issue by yelhousni** [Consensys/gnark-crypto#302]
Since `q0 == 1, q1 == 0, q2 == 0`, many functions can be optimised, but the arithmetic templates are dirty and need some refactoring to allow that cleanly (see #299).

**Comment by omerfirmak** [comment]
related https://github.com/ConsenSys/gnark-crypto/commit/eb8bce9077e582f7ef48a5af7f616b8bc8f0e731#r98859712
