### ISSUE TITLE
Size returned by (*PointAffine).SetBytes for bw761

### ISSUE THREAD

**Issue by myrade** [ConsenSys/gnark-crypto#34]
Shouldn't it be equal to `sizePointCompressed`? https://github.com/ConsenSys/gurvy/blob/master/bw761/twistededwards/point.go#L127
Likewise are the lengths in the comments on lines 95-96 correct?

**Comment by gbotrel** [comment]
It seems indeed the comments don't match the function (ie compressed vs not compressed). 
Thanks for raising the issue :) --
