### ISSUE TITLE
Regarding the FFT parallelization barrier

### ISSUE THREAD

**Issue by weikengchen** [ConsenSys/gnark-crypto#340]
I did a benchmark of FFT regarding parallelization with many cores. Below is the result that I collect. 
It seems that when the number of cores goes beyond a certain number, parallelization on FFT with more computation resource is no longer useful? Thoughts?

16-logical-processor local machine:
2^16   2182754 ns/op
2^22   185430292 ns/op
2^23   390132789 ns/op
2^24   792266378 ns/op        
2^25   1681734267 ns/op

64-vCPU AWS server (c6gn.16xlarge):
2^16   2687069 ns/op
2^22   131809930 ns/op
2^23   272491346 ns/op
2^24   580313836 ns/op    
2^25   1192373908 ns/op

**Comment by weikengchen** [comment]
Some additional results seem to suggest that bit reversal may have a lot to do here:

16-vCPU AWS server (c5.4xlarge):
2^16   BenchmarkFFT-16              361            3330826 ns/op
2^16   BenchmarkFFT-16              584            2057060 ns/op  (without bit-reverse)
2^25   BenchmarkFFT-16                1        2085356631 ns/op
2^25   BenchmarkFFT-16                1        1140960977 ns/op  (without bit-reverse)

32-vCPU AWS server (c5a.8xlarge):
2^16  BenchmarkFFT-32              458            2658424 ns/op
2^16  BenchmarkFFT-32              672            1777500 ns/op   (without bit-reverse)
2^25  BenchmarkFFT-32                1        1749853826 ns/op
2^25  BenchmarkFFT-32                2          650107132 ns/op   (without bit-reverse)

**Comment by weikengchen** [comment]
I think this leaves the following question: is it worthy to have bit reversal?

**Comment by weikengchen** [comment]
A simple parallelization for BitReverse appears to be useful. 
BenchmarkFFT-16                1        1634912154 ns/op (sequential bit reversal)
BenchmarkFFT-16                1        1188077247 ns/op (parallel bit reversal)
BenchmarkFFT-16                1        1091212294 ns/op (no bit reversal)

**Comment by gbotrel** [comment]
there is quite possibly some room for improvement in the FFT impl. On the zkSNARK provers (gnark side), we're indeed careful to minimize `BitReverse` operations, and very often do several FFT in parallel (as in, even with a 96core machine, a single FFT might actually only consume couple of threads). 

That being said, measuring improvements on the FFT is quite tricky, because it's memory heavy and cache friendliness matters a lot. Field size & FFT size will probably dictate different strategies -- if you have suggestions in mind, feel free to share 👍

**Comment by weikengchen** [comment]
I will carefully consider the approach of doing multiple FFT in parallel. As you can see, I am looking for linear scalability.

**Comment by weikengchen** [comment]
I think the issue has been sufficiently discussed. Closed.
