### ISSUE TITLE
feat: make fp.SetBigInt with value > modulus behaviour configurable.

### ISSUE THREAD

**Issue by omerfirmak** [ConsenSys/gnark-crypto#346]
Currently element is set to `value % modulus`, either make SetBigInt configurably return an error when `value > modulus` or introduce a new function with such behaviour.

**Comment by omerfirmak** [comment]
ideally, this feature should be propagated to the functions that use SetBigInt under the hood.

**Comment by gbotrel** [comment]
What you are looking for is: 
```
// SetBytesCanonical interprets e as the bytes of a big-endian 32-byte integer.
// If e is not a 32-byte slice or encodes a value higher than q,
// SetBytesCanonical returns an error.
func (z *Element) SetBytesCanonical(e []byte) error {
```

(see also `fp.LittleEndian` or `fp.BigEndian` object docs 👍 )

**Comment by omerfirmak** [comment]
Yeap, thanks!
