### ISSUE TITLE
Test vectors for hash2curve for bn254

### ISSUE THREAD

**Issue by man2706kum** [Consensys/gnark-crypto#412]
The IETF draft does not have any test vectors for hash2curve for bn254 pairing curve. How was the test vector (https://github.com/ConsenSys/gnark-crypto/blob/master/ecc/bn254/hash_vectors_test.go) generated for the same?

**Comment by gbotrel** [comment]
cc @Tabaie

**Comment by Tabaie** [comment]
Generated here: https://github.com/Tabaie/h2c-go-ref-tests/blob/autogen-tests/gnark_autogen_test.go#L145
This repo is a fork of [h2c-go-ref](https://github.com/armfazh/h2c-go-ref) by Armando Faz, one of the standard's authors.

**Comment by man2706kum** [comment]
The repo which you mentioned(https://github.com/Tabaie/h2c-go-ref-tests/blob/autogen-tests/gnark_autogen_test.go#L145) is showing not available. May be the repo is private i guess.

**Comment by man2706kum** [comment]
yes! I can see it. Thank you so much @Tabaie !!!
