### ISSUE TITLE
bug: possibly incorrect `DST_prime` in `ExpandMsgXmd`

### ISSUE THREAD

**Issue by hussein-aitlahcen** [Consensys/gnark-crypto#477]
Unless I am missing something, it look like instead of `DST_prime = I2OSP(len(DST), 1) ∥ DST`, we do `DST_prime = DST || I2OSP(len(DST), 1) ` in:
- https://github.com/Consensys/gnark-crypto/blob/eb75782795d2d3ce6172797615f8eada77a6a3dd/field/hash/hashutils.go#L37-L40
- https://github.com/Consensys/gnark-crypto/blob/eb75782795d2d3ce6172797615f8eada77a6a3dd/field/hash/hashutils.go#L53-L56
- https://github.com/Consensys/gnark-crypto/blob/eb75782795d2d3ce6172797615f8eada77a6a3dd/field/hash/hashutils.go#L77-L80

**Comment by ivokub** [comment]
Indeed, I also encountered it some time ago. I'd have to recheck, but imo it was due to different versions of the RFC we implemented hash-to-field from.

**Comment by hussein-aitlahcen** [comment]
> Indeed, I also encountered it some time ago. I'd have to recheck, but imo it was due to different versions of the RFC we implemented hash-to-field from.

I figured out while rewriting this in a gnark circuit... Do you want me to open a PR or we consider this to be fine (maybe backward compatibility would be hurt here)?

**Comment by ivokub** [comment]
So, we have referenced version 06 in the code, but actually implemented the final version, see: https://datatracker.ietf.org/doc/html/rfc9380.

**Comment by ivokub** [comment]
Indeed, it would already hurt backwards compatibility as we also implement hash-to-field in the Solidity smart contract verifier and the current PLONK version we have is audited, so cannot modify easily anymore.

**Comment by hussein-aitlahcen** [comment]
Ah the implementation is correct then, let me just change the reference in case anyone hit this again haha. Thanks for the quick answer!

**Comment by ivokub** [comment]
It would be perfect!
