### ISSUE TITLE
📦 `github.com/consensys/gnark-crypto/ecc`

### ISSUE THREAD

**Issue by Nidacoke** [Consensys/gnark-crypto#502]
📦 `github.com/consensys/gnark-crypto/ecc`
❌ `TestNafDecomposition` 0s
```
    utils_test.go:19: Error in NafDecomposition
    utils_test.go:19: Error in NafDecomposition
    utils_test.go:19: Error in NafDecomposition
    utils_test.go:19: Error in NafDecomposition
    utils_test.go:19: Error in NafDecomposition
```

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_cios_0064`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_cios_0128`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_cios_0192`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_cios_0256`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_cios_0320`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_cios_0384`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_cios_0448`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0061`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0062`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0063`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0065`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0125`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0126`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0127`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0129`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0189`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0190`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0191`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0193`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0253`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0254`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0255`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0257`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0317`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0318`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0319`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0321`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0381`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0382`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0383`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0385`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0445`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0446`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0447`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_0449`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_edge_0127`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_nocarry_edge_1279`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/e_secp256k1`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/forty_seven`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/small`

📦 `github.com/consensys/gnark-crypto/field/generator/integration_test/small_without_no_carry`

_Originally posted by @github-actions[bot] in https://github.com/Consensys/gnark-crypto/issues/460#issuecomment-1760190885_

**Comment by ivokub** [comment]
Can you describe the issue?
