### ISSUE TITLE
build failed when GOARCH=arm64

### ISSUE THREAD

**Issue by learnergo** [ConsenSys/gnark-crypto#73]
baidudeMacBook-Pro:09$ GOOS=linux GOARCH=arm64 go build
# github.com/consensys/gurvy/bls377/fr
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bls377/fr/element.go:517:2: undefined: fromMontElement
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bls377/fr/element.go:530:2: undefined: mulAssignElement
# github.com/consensys/gurvy/bls381/fr
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bls381/fr/element.go:517:2: undefined: fromMontElement
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bls381/fr/element.go:530:2: undefined: mulAssignElement
# github.com/consensys/gurvy/bn256/fr
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bn256/fr/element.go:517:2: undefined: fromMontElement
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bn256/fr/element.go:530:2: undefined: mulAssignElement
# github.com/consensys/gurvy/bn256/fp
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bn256/fp/element.go:517:2: undefined: fromMontElement
/opt/gopath/pkg/mod/github.com/consensys/gurvy@v0.1.2-0.20200512111154-1662e289e29b/bn256/fp/element.go:530:2: undefined: mulAssignElement

**Comment by gbotrel** [comment]
Hi -- seems you're pointing to a very old version of the repo. 

Project name is `gnark-crypto`, not `gurvy` anymore, and we're at version `v0.5.X` . Can you update and give it a try? (some of us work on ARM laptops with no issues).
