### ISSUE TITLE
Quadruple-and-add for BLS24 Miller loop

### ISSUE THREAD

**Issue by yelhousni** [Consensys/gnark-crypto#79]
Similarly to BLS12 curves, BLS24 Miller loop counter is the curve seed `u`. Although this seed is 32 bits (half the size of BLS12 seeds), the BLS24 Miller loop is slower. This is mainly because the most costly operations encountered in the Miller loop computation are those that take place in the full extension field `Fp24`. Implementing this paper's [[CBNW10]](https://eprint.iacr.org/2010/104.pdf) quadruple-and-add algorithm would reduce operations in `Fp24` (see section 6 for comparisons).

**Comment by Raneet10** [comment]
Hi! Has this been or being worked on ? In case it hasn't been (or isn't being), I would like to take a stab at it, given that it's a good first issue. Thanks!

**Comment by yelhousni** [comment]
> Hi! Has this been or being worked on ? In case it hasn't been (or isn't being), I would like to take a stab at it, given that it's a good first issue. Thanks!

Hi @Raneet10 ! No this is still an open issue — go for it! It might become handy in the near future.

**Comment by yelhousni** [comment]
BLS24 is low priority today so closing this.
