### ISSUE TITLE
Batch subgroup check

### ISSUE THREAD

**Issue by gbotrel** [Consensys/gnark-crypto#94]
When deserializing points (see ecc/xxx/Decoder) , we do a subgroup check. 

`gnark` may need to deserialize millions of such points, and performance wise, we can't afford to do multiple scalar multiplication per point.

See (?):
* https://cseweb.ucsd.edu/~mihir/papers/batch.pdf

**Comment by yelhousni** [comment]
@gbotrel Is this still an issue?

**Comment by gbotrel** [comment]
Not a pressing one; in prod scenarios I'm aware of (i.e. with large number of points), provenance of the points is trusted and we skip subgroup checks anyway for fast de-serialization.
